### ISSUE TITLE
Sample do not show map.

### ISSUE THREAD

**Issue by astrokin** [CartoDB/mobile-ios-samples#1]
Sample app do not show map and send error to concole:

`<Error>: LicenseManager::verifyLicenseParameters: Invalid product`

**Comment by astrokin** [comment]
@Nikituh could you please provide any comments about this issue?

**Comment by Nikituh** [comment]
@astrokin  Oh, sorry. Cannot reproduce, the entire structure of the repository has been changed and everything seems to work.

**Comment by mtehver** [comment]
It seems that AdvancedMap sample contains license for Nutiteq SDK version 3, not CARTO Mobile SDK 4.

**Comment by Nikituh** [comment]
updated license

**Comment by shinriyo** [comment]
Where can we find License on the mypage?

**Comment by shinriyo** [comment]
@astrokin Did you find it finally?
