### ISSUE TITLE
Shapefiles

### ISSUE THREAD

**Issue by igor9silva** [CartoDB/mobile-ios-samples#10]
Hi, are there any examples showing how to render a shapefile over a map?

**Comment by Nikituh** [comment]
Hey there,

Shapefiles aren't supported in our standard SDK (possible with GDAL build, but there aren't any recent binaries available). You need to manually convert it to geojson or mbtiles.

**Comment by igor9silva** [comment]
We ended up implementing it by reading the Shapefiles manually and drawing them as regular CARTO Polygons.

For iOS we've used: 
https://github.com/grgcombs/iOS-Shapefile - **For parsing the Shapefiles (.shp, .shx)** - We hacked it since it'd return MapKit polygons instead of a collection of coordinates. Anyone in need feel free to contact me to get our implementation. 
https://github.com/woodnathan/DBF-Reader/ - **To read Shapefile's metadata (.dbf)**

For Android we've used:
https://github.com/diwi/diewald_shapeFileReader - **For parsing .shp, .shx and .dbf**

**Comment by jaakla** [comment]
Thanks for letting us know, priceless references. This could be optimal solution, as the GDAL/OGR what we have compiled in supports tens of formats but it also very big and complex.
