### ISSUE TITLE
Use Cocoapod for all projects to get SDK

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-ios-samples#2]

**Comment by jaakla** [comment]
Dependent on sdk preversion build and trunk publish by @mtehver

**Comment by mtehver** [comment]
- build-ios.py script has now support for Cocoapod building (--build-cocoapod argument)
- For Jenkins CI, `$BUILD_NUMBER` should be replaced with ``printf "%0.3i" $BUILD_NUMBER`` (note the REQUIRED backward ticks here). This applies to nuget builds also.
