### ISSUE TITLE
Add version number to header

### ISSUE THREAD

**Issue by astrokin** [CartoDB/mobile-ios-samples#4]
It would be great to have a framework version number in header file.

**Comment by jaakla** [comment]
Loaded version number is in Podfile.lock . Would this work for you?

**Comment by astrokin** [comment]
@jaakla thank you. I could not find  *.podspec in master branch but later checked out sample Podfile and found `CartoMobileSDK`. It's ok for now. Issue can be closed, but it would be gteat to add installation instruction. Something like `pod 'CartoMobileSDK'` or `pod install CartoMobileSDK`.
