### ISSUE TITLE
Numerous failed to load tile errors

### ISSUE THREAD

**Issue by tymur-mamedov-epam** [CartoDB/mobile-ios-samples#5]
A lot of map tiles are not getting loaded. ![tilesissue](https://cloud.githubusercontent.com/assets/1395105/19444591/ba76338a-9499-11e6-8596-5c97fe4684ec.png)
I've tried London, San Francisco and New York locations (simulated in Xcode).
I get a lot of errors like these:
Oct 17 18:26:20  libg-cap[41752] <Error>: CartoOnlineTileDataSource::loadOnlineTile: Failed to load tile 14/4824/6157
Oct 17 18:26:20  libg-cap[41752] <Info>: MemoryCacheTileDataSource::loadTile: Failed to load MapTile [x=4824, y=6157, zoom=14, frameNr=0, id=190359597].
Oct 17 18:26:20  libg-cap[41752] <Error>: CartoOnlineTileDataSource::loadOnlineTile: Failed to load tile 14/4824/6157
Oct 17 18:26:20  libg-cap[41752] <Info>: MemoryCacheTileDataSource::loadTile: Failed to load MapTile [x=4824, y=6157, zoom=14, frameNr=0, id=190359597].

**Comment by mtehver** [comment]
Sorry for the delayed response and thanks for reporting this. Does the problem still persist? 2 weeks ago we were migrating some online services and there could have been some downtime.

**Comment by tymur-mamedov-epam** [comment]
Thanks for getting back to me on this. This issue is no longer reproducible and you can close it now.

**Comment by mtehver** [comment]
Thanks for the feedback. Closing now.
