### ISSUE TITLE
X and Y coordinates seem to be mixed in Carto SDK for iOS and Android

### ISSUE THREAD

**Issue by tymur-mamedov-epam** [CartoDB/mobile-ios-samples#6]
Here is what my app is doing:
 1) Detects phone's GPS coordinates
 2) Converts coordinates into map projection
 3) Displays marker on Carto Map

Actual result:
- Marker is displayed on a completely wrong position

Workaround:
- After step 1 above swap X and Y coordinates - then everything works fine

Notes:
- We observe such Carto SDK behavior on both iOS and Android

**Comment by mtehver** [comment]
This probably an issue of conventions (and not the issue of SDK). If you use Projection class to convert WGS84 coordinates, then CartoSDK uses longitude/latitude ordering for 'fromWgs84' method. Note that there is also a 'fromLatLong' method that uses flipped ordering. Closing this for now.

**Comment by tymur-mamedov-epam** [comment]
The documentation for fromWgs84 indeed says that it expects longitude-latitude ordering. Thanks for pointing this out to me.
