### ISSUE TITLE
Carto SQL API fails to reply within 60 seconds

### ISSUE THREAD

**Issue by tymur-mamedov-epam** [CartoDB/mobile-ios-samples#7]
Quite often [Carto SQL API](https://carto.com/docs/carto-engine/sql-api/making-calls/#json) fails to reply within 60 seconds. While other requests take a few seconds or less.

**Comment by mtehver** [comment]
Could this be related to the query you are using? 60 seconds usually means either a very complex query or huge number of query results.

**Comment by tymur-mamedov-epam** [comment]
It seems to be failing for zoom level 1 or 2. It does not seem to be failing for zoom level 3, even though the structure of the query and the number of results for this zoom level is the same.

**Comment by mtehver** [comment]
Any chance you could share your code? If you try to use SQL API directly (via browser, for example), do you get results without delay?

**Comment by Nikituh** [comment]
Closing, as it no longer relevant: we cannot reproduce and @tymur-mamedov-epam is MIA.
