### ISSUE TITLE
Long route takes a lot of memory

### ISSUE THREAD

**Issue by jaakla** [CartoDB/mobile-ios-samples#8]
During parsing and adding Markers for a long route (hundreds of instructions) a lot of memory is temporarily required. For example route across Africa could be 1000 instructions, and on iOS sample it shows for a moment about 1G of memory, which is immediately released. Seems to related to creating markers for instructions, not rendering itself. Later rendering works fine, and does not consume memory anymore.

Tested on ObjC AdvancedMap

**Comment by mtehver** [comment]
Fixed now, new version is also much faster when constructing route markers. The fix may have to be ported to Android/.NET samples also.
